SUBROUTINE STDB_ABQERR(I, MSG, INTV, REALV, CHARV)
  IMPLICIT NONE
  INTEGER :: I
  CHARACTER*120 :: MSG
  INTEGER :: INTV(1), IDUM
  REAL(8) :: REALV(1), RDUM
  CHARACTER*8 :: CHARV(1), CDUM(1)
  CHARACTER*200 JNKSTR
  EXTERNAL LOG_MESSAGE
  EXTERNAL LOG_ERROR
  EXTERNAL LOG_WARNING
  RDUM=REALV(1)
  IDUM=INTV(1)
  CDUM=CHARV(1)
  IF (I == -3) THEN
     JNKSTR = "ABA: BOMBED: " // MSG
     PRINT*, JNKSTR
     stop
  ELSE IF (I == -1) THEN
     PRINT*, MSG
  ELSE IF (I == -2) THEN
     JNKSTR = "ABA: ERROR: " // MSG
     PRINT*, JNKSTR
  ELSE
     PRINT*, MSG
  END IF
  RETURN
END SUBROUTINE STDB_ABQERR
