#!/usr/bin/env python
import os
import sys
import argparse

gmd_d = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, os.path.join(gmd_d, 'utils', 'exo'))

import exodiff

def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]
    parser = argparse.ArgumentParser()
    parser.add_argument("-f",
        help=("Use the given file to specify the variables to be considered "
              "and to what tolerances [default: %(default)s]."))
    parser.add_argument("--interp", default=False, action="store_true",
        help=("Interpolate variabes through time to compute error "
              "[default: %(default)s]."))
    parser.add_argument("source1")
    parser.add_argument("source2")
    args = parser.parse_args(argv)
    return exodiff.exodiff(args)


if __name__ == "__main__":
    sys.exit(main())
