#!/bin/bash
# set up python environment
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="$(dirname "$DIR")"
UTIL="$ROOT/utils"
PYFILE="$ROOT/core/testing.py"
export PYTHONPATH="$ROOT"
/usr/bin/env python $PYFILE $*