SUBROUTINE UMAT(STRESS, STATEV, DDSDDE, SSE, SPD, SCD, RPL, &
     DDSDDT, DRPLDE, DRPLDT, STRAN, DSTRAN, TIME, DTIME, TEMP, DTEMP, &
     PREDEF, DPRED, CMNAME, NDI, NSHR, NTENS, NSTATV, PROPS, NPROPS, &
     COORDS, DROT, PNEWDT, CELENT, DFGRD0, DFGRD1, NOEL, NPT, LAYER, &
     KSPT, KSTEP, KINC)

  IMPLICIT NONE
  REAL(8), PARAMETER :: ZERO=0.E+00_8, ONE=1.E+00_8, TWO=2.E+00_8
  REAL(8), PARAMETER :: THREE=3.E+00_8, SIX=6.E+00_8
  CHARACTER*8, INTENT(IN) :: CMNAME
  INTEGER, INTENT(IN) :: NDI, NSHR, NTENS, NSTATV, NPROPS
  INTEGER, INTENT(IN) :: NOEL, NPT, LAYER, KSPT, KSTEP, KINC
  REAL(8), INTENT(IN) :: SSE, SPD, SCD, RPL, DRPLDT, TIME, DTIME, TEMP, DTEMP
  REAL(8), INTENT(IN) :: PNEWDT, CELENT
  REAL(8), INTENT(INOUT) :: STRESS(NTENS), STATEV(NSTATV), DDSDDE(NTENS, NTENS)
  REAL(8), INTENT(INOUT) :: DDSDDT(NTENS), DRPLDE(NTENS)
  REAL(8), INTENT(IN) :: STRAN(NTENS), DSTRAN(NTENS)
  REAL(8), INTENT(IN) :: PREDEF(1), DPRED(1), PROPS(NPROPS), COORDS(3)
  REAL(8), INTENT(IN) :: DROT(3, 3), DFGRD0(3, 3), DFGRD1(3, 3)

  RETURN
END SUBROUTINE UMAT
