#!/usr/bin/env python
import os
import sys
d = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.dirname(d))
from matmodlab import *
import viz.main
sys.exit(main(argv=sys.argv[1:]))
