MODULE NUMBERS
  INTEGER, PARAMETER :: DP=SELECTED_REAL_KIND(14)

  REAL(KIND=DP), PARAMETER :: ZERO=0._DP
  REAL(KIND=DP), PARAMETER :: ONE=1._DP
  REAL(KIND=DP), PARAMETER :: TWO=2._DP
  REAL(KIND=DP), PARAMETER :: THREE=3._DP
  REAL(KIND=DP), PARAMETER :: FOUR=4._DP
  REAL(KIND=DP), PARAMETER :: SIX=6._DP
  REAL(KIND=DP), PARAMETER :: TEN=10._DP
  REAL(KIND=DP), PARAMETER :: TWELVE=12._DP
  REAL(KIND=DP), PARAMETER :: THIRTY=30._DP

  REAL(KIND=DP), PARAMETER :: P12TH=ONE/TWELVE
  REAL(KIND=DP), PARAMETER :: P6TH=ONE/SIX
  REAL(KIND=DP), PARAMETER :: P4TH=ONE/FOUR
  REAL(KIND=DP), PARAMETER :: P3RD=ONE/THREE
  REAL(KIND=DP), PARAMETER :: HALF=ONE/TWO
  REAL(KIND=DP), PARAMETER :: P23RD=TWO/THREE
  REAL(KIND=DP), PARAMETER :: P3HALF=THREE/TWO

  REAL(KIND=DP), PARAMETER :: RT23RD=8.16496580927726034460079063137528E-01_DP
  REAL(KIND=DP), PARAMETER :: ROOT2=0.1414213562373095048801688724209698078E+01_DP
  REAL(KIND=DP), PARAMETER :: TOOR2=0.7071067811865475244008443621048490392E+00_DP
  REAL(KIND=DP), PARAMETER :: RTPI=1.772453850905515881919427556567825E+00_DP

  REAL(KIND=DP), PARAMETER :: BIGNUM=1.E+30_DP
  REAL(KIND=DP), PARAMETER :: E20=1.E+20_DP

  REAL(KIND=DP), PARAMETER :: EM1=1.E-01_DP
  REAL(KIND=DP), PARAMETER :: EM3=1.E-3_DP
  REAL(KIND=DP), PARAMETER :: EM4=1.E-4_DP
  REAL(KIND=DP), PARAMETER :: EM10=1.E-10_DP
  REAL(KIND=DP), PARAMETER :: EM30=1.E-30_DP
  REAL(KIND=DP), PARAMETER :: MACHINE_EPSILON=EPSILON(ONE)

  REAL(KIND=DP), PARAMETER :: POINT03=.03_DP
  REAL(KIND=DP), PARAMETER :: TOLER=3.0001E+00_DP

  ! FOR MESSAGES TO BE SENT TO ABAQUS
  INTEGER, PARAMETER :: IMSG=1
  INTEGER, PARAMETER :: IWRN=-1
  INTEGER, PARAMETER :: IERR2=-2
  INTEGER, PARAMETER :: IERR=-3

CONTAINS

  LOGICAL FUNCTION EQ(A, B)
    ! IS A == B?
    REAL(KIND=DP), INTENT(IN) :: A, B
    EQ = ABS(A - B) <= MACHINE_EPSILON
    RETURN
  END FUNCTION EQ

  LOGICAL FUNCTION NOTEQ(A, B)
    ! IS A /= B?
    REAL(KIND=DP), INTENT(IN) :: A, B
    NOTEQ = .NOT. EQ(A, B)
    RETURN
  END FUNCTION NOTEQ

  LOGICAL FUNCTION LEQ(A, B)
    ! IS A <= B?
    REAL(KIND=DP), INTENT(IN) :: A, B
    LEQ = (A - B) <= ZERO
    RETURN
  END FUNCTION LEQ

  LOGICAL FUNCTION GEQ(A, B)
    ! IS A <= B?
    REAL(KIND=DP), INTENT(IN) :: A, B
    GEQ = (A - B) >= ZERO
    RETURN
  END FUNCTION GEQ

  LOGICAL FUNCTION LT(A, B)
    ! IS A < B?
    REAL(KIND=DP), INTENT(IN) :: A, B
    LT = (A - B) < ZERO
    RETURN
  END FUNCTION LT

  LOGICAL FUNCTION GT(A, B)
    ! IS A > B?
    REAL(KIND=DP), INTENT(IN) :: A, B
    GT = (A - B) > ZERO
    RETURN
  END FUNCTION GT

END MODULE NUMBERS
